# Generated by Django 3.0.5 on 2020-05-22 03:54

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('slack_workplace_id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('slack_bot_user_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('slack_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('slack_enabled', models.BooleanField(blank=True, null=True)),
                ('slack_timezone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('slack_timezone_override', models.BooleanField(blank=True, null=True)),
                ('slack_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.SlackWorkspace')),
            ],
        ),
    ]
